### ISSUE TITLE
Issue with hide without animation

### ISSUE THREAD

**Issue by matpaul** [TargetProcess/tau-tooltip#2]
@Mavrin Hello!
On this line 
https://github.com/TargetProcess/tau-tooltip/blob/76e1eaf7633fff55c09c91e13e67efa3800ccc13/src/tooltip.js#L110

incorrect usage of getComputedStyle
That is why tooltip disappears without animation

The fix for that  is something like  
`var duration = String(style(element).getPropertyValue('transition-duration'));`

**Comment by SelenIT** [comment]
It seems that `String(style(element)[transitionDuration.propName])` should also work.

**Comment by Mavrin** [comment]
@matpaul Fixed in 1.1.3.  Thank you for contributions.
